apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: production
spec:
  selector:
    app: db
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  externalTrafficPolicy: Local
  type: LoadBalancer
