apiVersion: v1
kind: Service
metadata:
  name: node-graphql-kit
spec:
  selector:
    app: node-graphql-kit
  ports:
    - port: 9000
      name: myservice
      targetPort: 9000
    - port: 5432
      name: db
      targetPort: 5432
  externalTrafficPolicy: Local
  type: LoadBalancer
