apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-kit
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-kit
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
